In [9]:
from sklearn.datasets import load_wine

wine_data = load_wine()
wine_data

{'DESCR': '.. _wine_dataset:\n\nWine recognition dataset\n------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 178 (50 in each of three classes)\n    :Number of Attributes: 13 numeric, predictive attributes and the class\n    :Attribute Information:\n \t\t- Alcohol\n \t\t- Malic acid\n \t\t- Ash\n\t\t- Alcalinity of ash  \n \t\t- Magnesium\n\t\t- Total phenols\n \t\t- Flavanoids\n \t\t- Nonflavanoid phenols\n \t\t- Proanthocyanins\n\t\t- Color intensity\n \t\t- Hue\n \t\t- OD280/OD315 of diluted wines\n \t\t- Proline\n\n    - class:\n            - class_0\n            - class_1\n            - class_2\n\t\t\n    :Summary Statistics:\n    \n    ============================= ==== ===== ======= =====\n                                   Min   Max   Mean     SD\n    ============================= ==== ===== ======= =====\n    Alcohol:                      11.0  14.8    13.0   0.8\n    Malic Acid:                   0.74  5.80    2.34  1.12\n    Ash:           

In [12]:
keys = wine_data.keys()
keys

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])

In [18]:
print('\n feature_names 의 type:',type(wine_data.feature_names))
print(' feature_names 의 shape:',len(wine_data.feature_names))
print(wine_data.feature_names)

print('\n target_names 의 type:',type(wine_data.target_names))
print(' feature_names 의 shape:',len(wine_data.target_names))
print(wine_data.target_names)

print('\n data 의 type:',type(wine_data.data))
print(' data 의 shape:',wine_data.data.shape)
print(wine_data['data'])

print('\n target 의 type:',type(wine_data.target))
print(' target 의 shape:',wine_data.target.shape)
print(wine_data.target)


 feature_names 의 type: <class 'list'>
 feature_names 의 shape: 13
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']

 target_names 의 type: <class 'numpy.ndarray'>
 feature_names 의 shape: 3
['class_0' 'class_1' 'class_2']

 data 의 type: <class 'numpy.ndarray'>
 data 의 shape: (178, 13)
[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]

 target 의 type: <class 'numpy.ndarray'>
 target 의 shape: (178,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 

In [19]:
import pandas as pd
import numpy as np

df = pd.DataFrame(wine_data.data, columns=wine_data.feature_names)
df

alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
0      14.23        1.71  2.43  ...  1.04                          3.92   1065.0
1      13.20        1.78  2.14  ...  1.05                          3.40   1050.0
2      13.16        2.36  2.67  ...  1.03                          3.17   1185.0
3      14.37        1.95  2.50  ...  0.86                          3.45   1480.0
4      13.24        2.59  2.87  ...  1.04                          2.93    735.0
..       ...         ...   ...  ...   ...                           ...      ...
173    13.71        5.65  2.45  ...  0.64                          1.74    740.0
174    13.40        3.91  2.48  ...  0.70                          1.56    750.0
175    13.27        4.28  2.26  ...  0.59                          1.56    835.0
176    13.17        2.59  2.37  ...  0.60                          1.62    840.0
177    14.13        4.10  2.74  ...  0.61                          1.60    560.0

[178 rows x 13 columns]

In [20]:
df['target'] = wine_data.target
df

alcohol  malic_acid   ash  ...  od280/od315_of_diluted_wines  proline  target
0      14.23        1.71  2.43  ...                          3.92   1065.0       0
1      13.20        1.78  2.14  ...                          3.40   1050.0       0
2      13.16        2.36  2.67  ...                          3.17   1185.0       0
3      14.37        1.95  2.50  ...                          3.45   1480.0       0
4      13.24        2.59  2.87  ...                          2.93    735.0       0
..       ...         ...   ...  ...                           ...      ...     ...
173    13.71        5.65  2.45  ...                          1.74    740.0       2
174    13.40        3.91  2.48  ...                          1.56    750.0       2
175    13.27        4.28  2.26  ...                          1.56    835.0       2
176    13.17        2.59  2.37  ...                          1.62    840.0       2
177    14.13        4.10  2.74  ...                          1.60    560.0       2

[178 rows x 14 columns]

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
x_data = df.loc[:,'alcohol':'proline'] # 문제데이터
y_data = df.loc[:, 'target'] #정답데이터

In [68]:
x_train, x_test, y_train, y_test = train_test_split(
    x_data, # 문제 데이터
    y_data, # 정답 데이터
    test_size =0.2, # 비율(train,test)
    shuffle = True, # 셔플링 여부 
    random_state = 20 # 시드값 
    )

In [24]:
x_train, x_test, y_train, y_test

(     alcohol  malic_acid   ash  ...   hue  od280/od315_of_diluted_wines  proline
 1      13.20        1.78  2.14  ...  1.05                          3.40   1050.0
 67     12.37        1.17  1.92  ...  1.12                          3.48    510.0
 174    13.40        3.91  2.48  ...  0.70                          1.56    750.0
 64     12.17        1.45  2.53  ...  1.45                          2.23    355.0
 20     14.06        1.63  2.28  ...  1.09                          3.71    780.0
 ..       ...         ...   ...  ...   ...                           ...      ...
 148    13.32        3.24  2.38  ...  0.55                          1.62    650.0
 137    12.53        5.51  2.64  ...  0.82                          1.69    515.0
 156    13.84        4.12  2.38  ...  0.57                          1.64    480.0
 15     13.63        1.81  2.70  ...  1.28                          2.88   1310.0
 99     12.29        3.17  2.21  ...  1.42                          2.83    406.0
 
 [142 rows x 1

In [26]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(142, 13)
(142,)
(36, 13)
(36,)


In [27]:
from sklearn.neighbors import KNeighborsClassifier

In [97]:
knn = KNeighborsClassifier(n_neighbors = 7) 

In [98]:
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=7)

In [99]:
pred = knn.predict(x_test)
pred

array([1, 2, 0, 2, 1, 1, 2, 1, 1, 2, 0, 2, 2, 2, 0, 1, 1, 0, 0, 2, 2, 0,
       1, 0, 2, 2, 0, 2, 1, 1, 0, 1, 1, 2, 0, 0])

In [43]:
from sklearn.metrics import accuracy_score

In [100]:
jumsu = accuracy_score(y_test, pred)

jumsu #accuracy 

0.8055555555555556

In [45]:
from sklearn.svm import SVC

In [84]:
svc = SVC(kernel = 'rbf')
# kernel : 'linear' : 직선, 'rbf' : 곡선

In [85]:
svc.fit(x_train, y_train)

SVC()

In [86]:
pred2 = svc.predict(x_test)
pred2

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 2, 0, 1, 2, 2, 0, 1, 1, 0, 0, 2, 2, 0,
       1, 0, 1, 1, 0, 2, 1, 1, 2, 2, 1, 2, 0, 0])

In [87]:
jumsu2 = accuracy_score(y_test, pred2)

jumsu2

0.7222222222222222