<a href="https://colab.research.google.com/github/HYUN816/python_data_eng/blob/main/colab_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print('welcome')

welcome


In [3]:
# mount : 드라이브에 연결 
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/csv_data/005930.KS.csv')

In [6]:
df

Date   Open   High    Low  Close    Adj Close    Volume
0    2020-01-02  55500  56000  55000  55200  52537.17969  12993228
1    2020-01-03  56000  56600  54900  55500  52822.70703  15422255
2    2020-01-06  54900  55600  54600  55500  52822.70703  10278951
3    2020-01-07  55700  56400  55600  55800  53108.23828  10009778
4    2020-01-08  56200  57400  55900  56800  54059.99219  23501171
..          ...    ...    ...    ...    ...          ...       ...
358  2021-06-14  80800  80900  80500  80500  80500.00000  10550078
359  2021-06-15  80900  81200  80600  80900  80900.00000  10075685
360  2021-06-16  81500  81900  81100  81800  81800.00000  14999855
361  2021-06-17  81100  81300  80700  80900  80900.00000  14007385
362  2021-06-18  81100  81100  80500  80500  80500.00000  14916721

[363 rows x 7 columns]

In [9]:
import numpy as np

In [8]:
df2 = pd.DataFrame({"name":["hong","park"],
                    "age":[10,20]})

# datafame의 구성요소 : index, column

In [10]:
df2

name  age
0  hong   10
1  park   20

In [11]:
df2.index

RangeIndex(start=0, stop=2, step=1)

In [12]:
df2.values

array([['hong', 10],
       ['park', 20]], dtype=object)

In [13]:
df2.name

0    hong
1    park
Name: name, dtype: object

In [14]:
df2['name']

0    hong
1    park
Name: name, dtype: object

In [15]:
df2.name.index

RangeIndex(start=0, stop=2, step=1)

In [16]:
df2.name.values

array(['hong', 'park'], dtype=object)

In [17]:
# unwraping : 자료구조 변경 된것 
df2.name.values.tolist()

['hong', 'park']

In [18]:
# database tuple 은 record 

df3 = pd.DataFrame(data = [['hong',10],['park',20]], columns=['name','age'])

In [19]:
df3

name  age
0  hong   10
1  park   20

In [20]:
df3.dtypes

name    object
age      int64
dtype: object

In [21]:
df3['age'].astype(float)

# astype은 원본을 바꾸지 않는다  = 비파괴함수
# 원본을 바꾸는 함수 = 파괴함수

0    10.0
1    20.0
Name: age, dtype: float64

In [22]:
df3.dtypes

name    object
age      int64
dtype: object

In [23]:
df3['age'] = df3['age'].astype(float)

# = 은 ram에 저장하는 대입연산자 

In [24]:
df3.dtypes

name     object
age     float64
dtype: object

In [26]:
df3.describe()
# 숫자형만 가능 
# 숫자로 적혀있다고 하더라도 type 이 object인 경우 연산하지 않는다.

age
count   2.000000
mean   15.000000
std     7.071068
min    10.000000
25%    12.500000
50%    15.000000
75%    17.500000
max    20.000000

In [27]:
type(df3['name'])

pandas.core.series.Series

In [28]:
df3['name']

0    hong
1    park
Name: name, dtype: object

In [29]:
df3['name'].index

RangeIndex(start=0, stop=2, step=1)

In [30]:
df3['name'].values

array(['hong', 'park'], dtype=object)

In [31]:
type(df3['name'].values)

numpy.ndarray

In [33]:
mask = np.zeros(5)
mask

array([0., 0., 0., 0., 0.])

In [34]:
type(mask)

numpy.ndarray

In [36]:
mask2 = np.zeros((3,4))
mask2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
arr2 = np.array([[1,2,3],[4,5,6]], dtype = np.float64)
arr2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [39]:
arr3 = np.array([[7,8,9],[10,11,12]], dtype = np.float64)
arr3

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [41]:
arr2 + arr3 

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [42]:
arr2 * arr3 

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [43]:
arr2 - arr3

array([[-6., -6., -6.],
       [-6., -6., -6.]])

In [ ]:
 # 계산 결과를 나중에 사용하고 싶으면 파생변수로 저장하시오.