In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

In [ ]:
# 말뭉치 만들기

corpus = ["you konw I want your love",
          "l like you",
          "what should I do",
          "I hate you",
          "smile face"
          ]

In [ ]:
cv = CountVectorizer()

In [ ]:
## 1. 사전 만들기 -> fit()
## 2. 사전에 들어있는 id로 인코딩 -> transform()
## 3. 1,2 을 함께 처리하고자 하는 경우는 fit_transform()

In [ ]:
# 인코딩 : 데이터를 원하는 형태로 바꾸는 것 
cv.fit_transform(corpus).toarray()

array([[0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]])

In [ ]:
cv.vocabulary_

{'do': 0,
 'face': 1,
 'hate': 2,
 'konw': 3,
 'like': 4,
 'love': 5,
 'should': 6,
 'smile': 7,
 'want': 8,
 'what': 9,
 'you': 10,
 'your': 11}

In [ ]:
tfidf = TfidfVectorizer()

In [ ]:
tfidf.fit(corpus)

TfidfVectorizer()

In [ ]:
tfidf.transform(corpus)

<5x12 sparse matrix of type '<class 'numpy.float64'>'
	with 14 stored elements in Compressed Sparse Row format>

In [ ]:
tfidf.transform(corpus).toarray()

array([[0.        , 0.        , 0.        , 0.47412465, 0.        ,
        0.47412465, 0.        , 0.        , 0.47412465, 0.        ,
        0.3175268 , 0.47412465],
       [0.        , 0.        , 0.        , 0.        , 0.83088075,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.55645052, 0.        ],
       [0.57735027, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.57735027, 0.        , 0.        , 0.57735027,
        0.        , 0.        ],
       [0.        , 0.        , 0.83088075, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.55645052, 0.        ],
       [0.        , 0.70710678, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.70710678, 0.        , 0.        ,
        0.        , 0.        ]])

In [ ]:
sentence = ['i like like like hate smile']

In [ ]:
nd2array = cv.transform(sentence).toarray()
nd2array

array([[0, 0, 1, 0, 3, 0, 0, 1, 0, 0, 0, 0]])

In [ ]:
nd2array[0]

array([0, 0, 1, 0, 3, 0, 0, 1, 0, 0, 0, 0])

In [ ]:
nd2array2 = tfidf.transform(sentence).toarray()
nd2array2

array([[0.        , 0.        , 0.30151134, 0.        , 0.90453403,
        0.        , 0.        , 0.30151134, 0.        , 0.        ,
        0.        , 0.        ]])

In [ ]:
cv.inverse_transform(nd2array)

[array(['hate', 'like', 'smile'], dtype='<U6')]

In [ ]:
tfidf.inverse_transform(nd2array2)

[array(['hate', 'like', 'smile'], dtype='<U6')]

In [ ]:
feature_list = cv.get_feature_names()
feature_list

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['do',
 'face',
 'hate',
 'konw',
 'like',
 'love',
 'should',
 'smile',
 'want',
 'what',
 'you',
 'your']

In [ ]:
# dic <-- list

dictionary = dict()

In [ ]:
for index, element in enumerate(feature_list) :
  dictionary[index] = element
dictionary

{0: 'do',
 1: 'face',
 2: 'hate',
 3: 'konw',
 4: 'like',
 5: 'love',
 6: 'should',
 7: 'smile',
 8: 'want',
 9: 'what',
 10: 'you',
 11: 'your'}

In [ ]:
## 스팸을 나타내는 사전 만들기(단어10개)
## 스팸이 아닌 사전을 만들기(단어10개)

spam_dict = ["advertise", "promotion", "sales", "hu", "special", "sale","member", "company"]
ham_dict = ["order", "confirm", "check", "customer", "payment", "send", "general", "club"]

In [ ]:
cv.fit(spam_dict)

CountVectorizer()

In [ ]:
cv.vocabulary_

{'advertise': 0,
 'company': 1,
 'hu': 2,
 'member': 3,
 'promotion': 4,
 'sale': 5,
 'sales': 6,
 'special': 7}

In [ ]:
email = ["promotion!!! hu good sales sale check payment"]

In [ ]:
result1 = cv.transform(email).toarray()
result1

array([[0, 0, 1, 0, 1, 1, 1, 0]])

In [ ]:
cv.fit(ham_dict)

CountVectorizer()

In [ ]:
cv.vocabulary_

{'check': 0,
 'club': 1,
 'confirm': 2,
 'customer': 3,
 'general': 4,
 'order': 5,
 'payment': 6,
 'send': 7}

In [ ]:
result2 = cv.transform(email).toarray()
result2

array([[1, 0, 0, 0, 0, 0, 1, 0]])

In [ ]:
result2 = ham_fit.transform(email).toarray()
result2

array([[1, 0, 0, 0, 0, 0, 1, 0]])

In [ ]:
## result1의 0이 아닌 개수의 합, result2의 0이 아닌 개수의 합
result1_count =0
result2_count =0

In [ ]:
for item in result1[0] : 
    if(item!=0):
      result1_count = result1_count +1
result1_count

4

In [ ]:
for item in result2[0] : 
    if(item!=0):
      result2_count = result2_count +1
result2_count

2

In [ ]:
## 한글버전 

In [ ]:
spam_dict2 = ["광고", "홍보", "판매", "허경영", "특가", "세일","회원", "회사"]
ham_dict2 = ["주문", "확인", "체크", "고객", "지불", "배송", "일반", "동호회"]

In [ ]:
email2 = [" 광고 !! 허경영 good 세일 확인 지불"]

In [ ]:
cv2 = CountVectorizer()

In [ ]:
cv2.fit(spam_dict2)

CountVectorizer()

In [ ]:
result3 = cv2.transform(email2).toarray()
result3

array([[1, 1, 0, 0, 1, 0, 0, 0]])

In [ ]:
cv2.fit(ham_dict2)

CountVectorizer()

In [ ]:
result4 = cv2.transform(email2).toarray()
result4

array([[0, 0, 0, 0, 0, 1, 0, 1]])

In [ ]:
result3_count = 0
result4_count = 0

In [ ]:
for item in result3[0]:
  # print(item > 0)
  if (item != 0):
    result3_count = result3_count + 1
result3_count

for item in result4[0]:
  # print(item > 0)
  if (item != 0):
    result4_count = result4_count + 1
print(result3_count, result4_count)

3 2


### 감정분류기(영어ver)

In [ ]:
pos_dic =['happy','joyful', 'proud','optimistic','aroused','confident', 'respect']
neg_dic=['bad','unhappy','stressful','tired','disappointed','lonely','rejected']

In [ ]:
sen = [input('write sentence>> ').lower()]
sen

write sentence>> i am happy now because i passed the exam i am confident for everything but i was very stressful during preparing exam. i don't believe it. i am proud of me


["i am happy now because i passed the exam i am confident for everything but i was very stressful during preparing exam. i don't believe it. i am proud of me"]

In [ ]:
tfidf = TfidfVectorizer()

In [ ]:
tfidf.fit(pos_dic)

TfidfVectorizer()

In [ ]:
tfidf.vocabulary_

{'aroused': 0,
 'confident': 1,
 'happy': 2,
 'joyful': 3,
 'optimistic': 4,
 'proud': 5,
 'respect': 6}

In [ ]:
result_p = tfidf.transform(sen).toarray()
result_p

array([[0.        , 0.57735027, 0.57735027, 0.        , 0.        ,
        0.57735027, 0.        ]])

In [ ]:
tfidf.fit(neg_dic)

TfidfVectorizer()

In [ ]:
tfidf.vocabulary_

{'bad': 0,
 'disappointed': 1,
 'lonely': 2,
 'rejected': 3,
 'stressful': 4,
 'tired': 5,
 'unhappy': 6}

In [ ]:
result_n = tfidf.transform(sen).toarray()
result_n

array([[0., 0., 0., 0., 1., 0., 0.]])

In [ ]:
p_count = 0
n_count = 0

In [ ]:
for item in result_p[0]:
  if (item != 0):
    p_count = p_count + 1

for item in result_n[0]:
  if (item != 0):
    n_count = n_count + 1
print( p_count , n_count)

3 1


In [ ]:
if p_count > n_count : 
  print('positive')
elif p_count <n_count : 
  print('negative')
else : 
  print('neutral')

positive
